### PR TITLE
Added Elementalist pistol proficiency buffs.

### PR DESCRIPTION
**Pull request by jordanrye**
Added the bullet icons for the Elementalist pistol proficiency.

### CODE REVIEW

**Comment by LukAraujo** [comment]
Any updates on this?

**Comment by jordanrye** [comment]
I managed to get it building locally by updating the header path for semver.hpp in GW2Clarity and GW2Common. There is a separate PR for Common (https://github.com/Friendly0Fire/GW2Common/pull/1) that will need to be merged in first, assuming it doesn't cause its own build error.

**Comment by ZyphiraZircon** [comment]
Hi there, did this kick off a release build? Or do I have to build the project myself in order to update?

**Comment by jordanrye** [comment]
@ZyphiraZircon It doesn't kick off a release build, but if you go into the Actions tab you can get a nightly build containing the DLLs built for this pull request.

**Comment by ZyphiraZircon** [comment]
Sweet, earlier the artifact wasn't clickable/downloadable so I was like "is this right?" but now I see that it is, cheers!

**Pull request merged**
